name: Release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., 0.0.2)'
        required: true
        type: string

permissions:
  contents: write

env:
  PRODUCT_NAME: xcodeproj

jobs:
  build-and-release:
    name: Build Universal Binaries and Release
    runs-on: macos-15

    steps:
    - name: Checkout
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

    - name: Setup Xcode
      run: sudo xcode-select -s /Applications/Xcode_16.4.app/Contents/Developer

    - name: Get version
      id: version
      run: |
        if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
          echo "version=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
        else
          echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
        fi

    - name: Install Swiftly for Linux cross-compilation
      run: |
        # Install Swiftly using the official macOS method to user directory
        curl -O https://download.swift.org/swiftly/darwin/swiftly.pkg
        installer -pkg swiftly.pkg -target CurrentUserHomeDirectory
        rm swiftly.pkg
        
        # Add to PATH for current session
        echo "$HOME/.swiftly/bin" >> $GITHUB_PATH
        export PATH="$HOME/.swiftly/bin:$PATH"

    - name: Build Linux binaries
      run: ./scripts/build-linux.sh

    - name: Clean build directory before macOS build
      run: rm -rf .build

    - name: Build macOS binaries
      run: ./scripts/build-macos.sh

    - name: Test Binaries
      run: |
        # Test macOS binary
        chmod +x build/macos/universal/${{ env.PRODUCT_NAME }}
        build/macos/universal/${{ env.PRODUCT_NAME }} --version
        build/macos/universal/${{ env.PRODUCT_NAME }} --help
        
        # Test Linux binaries
        chmod +x build/linux/x86_64/${{ env.PRODUCT_NAME }}
        chmod +x build/linux/aarch64/${{ env.PRODUCT_NAME }}

    - name: Update Homebrew Formula
      run: |
        ./scripts/prepare-homebrew.sh "${{ steps.version.outputs.version }}" \
          "build/macos/${{ env.PRODUCT_NAME }}-${{ steps.version.outputs.version }}-macos-universal.tar.gz"

    - name: Commit Formula Update
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add Formula/xcodeproj.rb
        git commit -m "chore: update Formula for ${{ steps.version.outputs.version }}" || echo "No changes to commit"
        git push origin HEAD:main || echo "Failed to push changes"

    - name: Create Release and Upload All Assets
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        # Determine if prerelease
        PRERELEASE_FLAG=""
        if [[ "${{ steps.version.outputs.version }}" == *"alpha"* ]] || [[ "${{ steps.version.outputs.version }}" == *"beta"* ]] || [[ "${{ steps.version.outputs.version }}" == *"rc"* ]]; then
          PRERELEASE_FLAG="--prerelease"
        fi

        # Create release with all assets (macOS + Linux)
        gh release create "${{ steps.version.outputs.version }}" \
          --title "xcodeproj CLI ${{ steps.version.outputs.version }}" \
          --notes "" \
          $PRERELEASE_FLAG \
          build/macos/universal/${{ env.PRODUCT_NAME }} \
          build/macos/${{ env.PRODUCT_NAME }}-${{ steps.version.outputs.version }}-macos-universal.tar.gz \
          build/macos/${{ env.PRODUCT_NAME }}-${{ steps.version.outputs.version }}-macos-checksums.txt \
          build/linux/${{ env.PRODUCT_NAME }}-${{ steps.version.outputs.version }}-linux-x86_64.tar.gz \
          build/linux/${{ env.PRODUCT_NAME }}-${{ steps.version.outputs.version }}-linux-aarch64.tar.gz \
          build/linux/${{ env.PRODUCT_NAME }}-${{ steps.version.outputs.version }}-linux-checksums.txt
  
  publish-npm:
    name: Publish to npm
    needs: build-and-release
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        # Fetch the latest to get any formula updates
        fetch-depth: 0
        
    - name: Pull latest changes
      run: |
        git pull origin main || true
        
    - name: Setup Node.js
      uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
      with:
        node-version: '22'
        registry-url: 'https://registry.npmjs.org'
        
    - name: Get version
      id: version
      run: |
        if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
          echo "version=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
        else
          echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
        fi
        
    - name: Publish npm package
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: |
        # Check if version already exists on npm
        VERSION="${{ steps.version.outputs.version }}"
        if npm view "@ainame/xcodeproj-cli@$VERSION" version 2>/dev/null; then
          echo "Version $VERSION already published to npm, skipping..."
        else
          echo "Publishing version $VERSION to npm..."
          npm publish --access public
        fi

  test-linux-after-publish:
    name: Test Linux Compatibility (Post-Publish)
    needs: publish-npm
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      
    - name: Get version
      id: version
      run: |
        if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
          echo "version=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
        else
          echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
        fi

    - name: Wait for npm package propagation
      run: |
        echo "Waiting for npm package to propagate..."
        VERSION="${{ steps.version.outputs.version }}"
        
        # Wait up to 5 minutes for the package to be available
        for i in {1..30}; do
          if npm view "@ainame/xcodeproj-cli@$VERSION" version 2>/dev/null; then
            echo "Package version $VERSION is now available on npm"
            break
          else
            echo "Waiting for package to be available... (attempt $i/30)"
            sleep 10
          fi
        done

    - name: Setup Node.js
      uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
      with:
        node-version: '22'
        registry-url: 'https://registry.npmjs.org'

    - name: Run Native Linux Compatibility Tests
      run: |
        # Make scripts executable
        chmod +x scripts/test-linux-native.sh
        chmod +x scripts/test-core.sh
        
        # Run the native Linux compatibility tests (no Docker overhead)
        ./scripts/test-linux-native.sh
        
    - name: Upload test results on failure
      if: failure()
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      with:
        name: linux-compatibility-test-failure
        path: |
          /tmp/xcodeproj-linux-test-*
        retention-days: 7
        
    - name: Comment on failure
      if: failure()
      uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '❌ Linux compatibility tests failed after npm publish. Please check the logs and artifacts for details.'
          })